### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by lpalbou** [geneontology/web-gocam#9] opened 2018-08-03 19:04 UTC
The current Feedback component does not create GitHub tickets and there are discussions about using a 3rd party tool for handling feedbacks.
- [x] : Check if API to submit ticket to GitHub (yes: https://developer.github.com/v3/issues/)
- [ ] : Monitor discussion on other choices (e.g. tender)

**Comment by kltm** [comment] 2018-08-03 23:16
@lpalbou I'll fold this into a new feedback component issue for the public website project.

**Comment by kltm** [comment] 2018-08-03 23:16
Apologies--this is on me.

**Comment by kltm** [comment] 2018-08-03 23:34
now dupe of https://github.com/geneontology/go-site/issues/750

**Closed by kltm** 2018-08-03 23:34 UTC
Labels: enhancement, question
